name: Test Token Access

on: [push]

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check GH_TOKEN
        run: echo "GH_TOKEN is set"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEsN }}  # This should not throw an error if set correctly
